name = "Simple Snipcart Shop"
license = "MIT"
licenselink = "https://github.com/tylerjlawson/simple-snipcart-shop/blob/master/LICENSE"
description = "Single Page online marketplace designed to work with snipcart out of the box"
homepage = "https://github.com/tylerjlawson/simple-snipcart-shop"
tags = ['ecommerce', 'simple', 'white', 'one-page', 'business']
features = ['snipcart', 'responsive','scss','autoprefixer']
min_version = "0.60.0"
demosite = "https://gifted-thompson-4ca71a.netlify.app/"

[author]
  name = "tylerjlawson"
  homepage = "https://tyler-lawson.com/"

